### ISSUE TITLE
Simple alternative to JSX in LiveScript

### ISSUE THREAD

**Issue by chrisvfritz** [wolfflow/react-livescript-jsx#1]
This is not an "issue" with the repo, but I've been using a very simple replacement for JSX that I really like in combination with LiveScript, so [thought I'd share](https://gist.github.com/chrisvfritz/f3e76764c920325638fc).

**Comment by wolfflow** [comment]
There is more simple replacement for dom elements

``` livescript
window <<< React.DOM
```

But you'll have to use React.createElement for components
[Further details in my gist](https://gist.github.com/wolfflow/0d035ecd5fb418f273e2)

**Comment by chrisvfritz** [comment]
That's simpler, but I would argue undesirable. I personally don't want a bunch of single-character functions in my global scope, such a `a`, `p`, `i`, `g`, etc. Prefixing them with the dollar sign tells us that these are all DOM functions, then mapping `$` to `React.createElement` gives us a very nice extension that feels very natural (and functional), as `$p` is really just a partial function doing the same work as `$ 'p', ...`.

**Comment by wolfflow** [comment]
You're right, garbage in global scope is undesirable.

In real-world apps, I prefer to assign necessary tag functions this way: 

``` livescript
# some-component.ls
{h1, div, p, a, whatever} = React.DOM

module.exports = React.createClass do
  render: ->
    div do
      class-name: 'test'
      h1 null, 'foo'
      p null, 'bar'
```

**Comment by chrisvfritz** [comment]
This may come down to personal preference, but I'd much rather have nicely namespaced functions (anything beginning with `$` is a DOM element) in the global scope, than have to declare which subset of DOM elements I'd like to use in every component. To each their own.
